# Generated by Django 6.0.6 on 2026-07-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='naam')),
                ('phone', models.CharField(max_length=40, verbose_name='telefoon')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('message', models.TextField(blank=True, verbose_name='bericht')),
                ('calculator_inputs', models.JSONField(blank=True, null=True)),
                ('calculator_result', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(default='react_calculator', max_length=50)),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
