# Generated by Django 6.0.6 on 2026-07-20 17:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='calculation_report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage2_answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage2_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
