# Generated by Django 6.0.6 on 2026-07-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_alt',
            field=models.CharField(blank=True, help_text='Describe the cover image for accessibility and SEO.', max_length=160, verbose_name='Cover image alt text'),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Optional meta description for search engines. Keep around 150–160 characters.', verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Optional short title for Google. Keep under 60 characters.', max_length=70, verbose_name='SEO title'),
        ),
    ]
